FORWARD_SLASH = "/"
HEADER_END_LINE = "\r\n"
COMMA_SEPARATOR = ","

'''
STATUS Codes
'''

STATUS_OK = 200
STATUS_MOVED_PERMANENTLY = 301
STATUS_FOUND = 302
STATUS_UNMODIFIED = 304
STATUS_BAD_REQUEST = 400
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404
STATUS_REQUEST_TIMEOUT = 408
STATUS_PRECONDITION_FAILED = 412
STATUS_INTERNAL_SERVER_ERROR = 500
STATUS_NOT_IMPLEMENTED = 501
STATUS_HTTP_VERSION_NOT_SUPPORTED = 505
